### ISSUE TITLE
Question regarding my use-case

### ISSUE THREAD

**Issue by maisun** [SolarNetwork/nifty-modbus#9]
Hi,
Thanks for the project! I have an old heat pump with Modbus TCP protocol, I have configured OpenHAB to read/write values to known registers which works fine. However there is 1 register which I need to control cooling functionality which was not mentioned in the documentation. The register must exist and has value 0 (OFF) and 1 (ON), I basically need to find what address is that register. 
I'm thinking to use the library to write a small Java program to iterate over all possible registers (address 1000-5000) and find the ones that have value 0, then turn on the cooling, re-scan and find which ones are changed from 0 to 1.
Would it be possible to achieve what I want with this project? Many thanks in advance!

**Comment by msqr** [comment]
Hi there! You certainly could write a pretty simple Java app using Nifty Modbus to do what you need. However if your goal is only to discover the Modbus register you're interested in, then use that in OpenHAB, you might find a pre-built Modbus tool like [mbpoll](https://github.com/epsilonrt/mbpoll) an easier way to go, as you wouldn't have to code anything. You can get a binary version of`mbpoll` in (recent versions of) Debian Linux, for example, with

```sh
apt install mbpoll
```

**Comment by maisun** [comment]
> Hi there! You certainly could write a pretty simple Java app using Nifty Modbus to do what you need. However if your goal is only to discover the Modbus register you're interested in, then use that in OpenHAB, you might find a pre-built Modbus tool like [mbpoll](https://github.com/epsilonrt/mbpoll) an easier way to go, as you wouldn't have to code anything. You can get a binary version of`mbpoll` in (recent versions of) Debian Linux, for example, with
> 
> ```shell
> apt install mbpoll
> ```

Thank you for your reply! I’m new to ModBus so please forgive me if I ask something stupid.
I read the mbpoll document but failed to see how it can help me to find the address of the holding/register that I’m interested in. I need some sort of scanning tool that can tell me which registers are available and with certain current value (0). I know the range is from 1-6000, however I cannot simply poll all at once as Modbus rejects the range polling when any address is not valid. So my initial plan is to use a for loop to check registers one by one and list all that are available and have value 0. Then I switch on the cooling functionality, and check if any of the register changes from 0 to 1.
Does ModBus TCP have a way to list all valid registers that contains value? 
many thanks in advance!

**Comment by maisun** [comment]
Hi again,
I spent an hour to experiment the idea and surprising it was really quick to get the programming part working based on your sample code. So below is what I did:
`
public static void main(String[] args) {
		NettyTcpModbusClientConfig config = new NettyTcpModbusClientConfig("10.x.x.x", 502);
		config.setAutoReconnect(false);
		ModbusClient client = new TcpNettyModbusClient(config);
		HashMap<Integer, Short> map = new HashMap<>();
		try {
			client.start().get();
			int address = 1;
			int count = 9999;
			for(int i = address; i<=address+count; i++){
				ModbusMessage req = readHoldingsRequest(1, i, 1);
				RegistersModbusMessage res = client.send(req).unwrap(RegistersModbusMessage.class);
				if (res != null ) {
					short[] data = res.dataDecode();
					map.put(i, data[0]);
				}
			}
			System.out.println("PLEASE CHANGE ACTIVE COOLING!!!!!!!!!!!!!");
			Thread.sleep(3*60*1000);
			for(int i = address; i<=address+count; i++){
				ModbusMessage req = readHoldingsRequest(1, i, 1);
				RegistersModbusMessage res = client.send(req).unwrap(RegistersModbusMessage.class);
				if (res != null ) {
					short[] data = res.dataDecode();
					if(map.get(i) != data[0]){
						System.out.println("Found some changes to register " + i + ":" + map.get(i) + "->" + data[0]);
					}
				}
			}
		} catch (Exception e) {
			e.printStackTrace();
		} finally {
			client.stop();
		}
	}
`
The idea is to read all values into a hashmap, then make the change of the setting, then iterate over all registers again and observe which ones have been updated. Unfortunately in my case all changes are related to temperature sensors, so the vendor for some reason doesn't expose the functionality I need over ModBus:
`Found some changes to register 4699:45->65
Found some changes to register 4700:48->70
Found some changes to register 4713:344->346
Found some changes to register 5088:254->253
Found some changes to register 5152:250->245
Found some changes to register 5153:261->259
Found some changes to register 5154:254->253
Found some changes to register 5155:254->255
Found some changes to register 5156:270->268
Found some changes to register 5157:64->83
Found some changes to register 5159:250->245
Found some changes to register 5162:558->560
Found some changes to register 5163:407->415
Found some changes to register 5191:-206->-204
`

Nevertheless it was great to find your project here and it was really easy to code to detect changes of a range of registers. Thanks a lot and have a great weekend!

**Comment by msqr** [comment]
Nice! Glad to hear you had a good experience. Modbus does allow register addresses up to `0xFFFF` (65535), so it is _possible_ the register you're looking for is higher than `9999`. All the best wrangling that heat pump!
